name: Add New Bookmark

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the website'
        required: true
        type: string
      url:
        description: 'The full URL of the website'
        required: true
        type: string
      description:
        description: 'A short description of the website'
        required: true
        type: string
      category:
        description: 'Category for the bookmark (e.g., General, Software). If it doesn''t exist, it will be created.'
        required: true
        type: string

jobs:
  add_bookmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add or update bookmark
        run: |
          # Prepare variables
          BOOKMARK_NAME="${{ github.event.inputs.name }}"
          BOOKMARK_URL="${{ github.event.inputs.url }}"
          BOOKMARK_DESC="${{ github.event.inputs.description }}"
          CATEGORY_NAME="${{ github.event.inputs.category }}"

          # HTML for the new bookmark card, with proper indentation.
          NEW_CARD_HTML="                    <div class=\"card\">\\n                        <h3>${BOOKMARK_NAME}<\\/h3>\\n                        <p>${BOOKMARK_DESC}<\\/p>\\n                        <a href=\"${BOOKMARK_URL}\" class=\"btn\" target=\"_blank\">Open Site<\\/a>\\n                    <\\/div>"

          # Marker for the specific category
          CATEGORY_MARKER="<!-- CARDS_FOR_${CATEGORY_NAME}_END -->"

          # Check if the category already exists
          if grep -q "$CATEGORY_MARKER" bookmarks.html; then
            # Category exists, so insert the new card before its marker using sed replacement
            # This is more robust than the previous awk script.
            sed -i "s/$CATEGORY_MARKER/$NEW_CARD_HTML\\n                    $CATEGORY_MARKER/" bookmarks.html
          else
            # Category does not exist, so create a new section
            NEW_CATEGORY_MARKER="<!-- CARDS_FOR_${CATEGORY_NAME}_END -->"
            NEW_CATEGORY_HTML="            <section class=\"category-section\">\\n                <h2 class=\"category-title\">${CATEGORY_NAME}<\\/h2>\\n                <div class=\"card-grid\">\\n${NEW_CARD_HTML}\\n                    ${NEW_CATEGORY_MARKER}\\n                <\\/div>\\n            <\\/section>"
            MAIN_MARKER="<!-- NEW_CATEGORIES_HERE -->"

            # Insert the new category section before the main placeholder using sed replacement
            sed -i "s/$MAIN_MARKER/$NEW_CATEGORY_HTML\\n            $MAIN_MARKER/" bookmarks.html
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add bookmark '${{ github.event.inputs.name }}' to category '${{ github.event.inputs.category }}'"
          file_pattern: bookmarks.html
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions-bot@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions-bot@users.noreply.github.com>"
